<script LANGUAGE="JavaScript" SRC="../scripts/odimages.js"></script>
  <TABLE BORDER="0" width=100% CELLPADDING=0 cellspacing="0" id=header>	
  <TR>
  	<TD ALIGN=left valign="bottom" width="250" id=logo>
     <img border="0" src="../images/odlogo2.jpg" width="250" height="125" align="absleft" alt="Outdoor Depot: Camping, Hiking, Biking and Backpacing Gear"></td>
     <td></td>
     <TD ALIGN=right valign="bottom"><form method="POST" action="search.php"> Search: <input type=text name=search size=25>&nbsp; <button name=gobutton type=submit  onmouseover="swap('go', 'on');" onmouseout="swap('go', 'off');">
     <img src=images/ball_red.gif name="go" width="12" height="12" onmouseover="swap('go', 'on');" onmouseout="swap('go', 'off');"> Go
     </button></form>
     <br>
     <a href="index.php"><img border="0" src="../images/home.gif" name="home" align="bottom" width="100" height="32" onmouseover="swap('home', 'on');" onmouseout="swap('home', 'off');"></a>&nbsp;
     <a href="feedback.php"><img border="0" src="../images/feedback.gif" name="feedback" width="100" height="32" onmouseover="swap('feedback', 'on');" onmouseout="swap('feedback', 'off');"></a>&nbsp;
     <a href="shopping_cart.php"> <img border="0" src="../images/cart.gif" name="cart" width="100" height="32" onmouseover="swap('cart', 'on');" onmouseout="swap('cart', 'off');"></a></TD>
  </TR>
  </TABLE>