  <TABLE BORDER="0" width=100% CELLPADDING=3 cellspacing="0">	
  <TR>	
   <TD valign="top" class=linklist>
  <div id=linklist1>
    <ul><li><p>Camping Gear</li>
        <li><p>Hiking Gear</li>
        <li><p>Biking Gear</li>
        <li><p>Backpacking Gear</li>
        <li><a href="category5.php">Women's Clothes</a></li>
        <li><p>Men's Clothes</li>
        <li><p>Kid's Clothes</li>
</ul>
<br>
<ul>
        <li><p>About Us</li>
        <li><p>Contact Us</li>
        <li><p>Site Map</li>
        <li><p>Customer Service</li>	
        <ul>
          <li><p>How to Order</li>
          <li><p>Shipping and Returns</li>
          <li><p>Check on Your Order</li>
        </ul></ul>
        </div>
   </TD>
   <TD valign="top" id=content>