  <link rel="stylesheet" type="text/css" href="../od.css">
<table border=0 width=100% cellpadding=0 cellspacing=0>
<tr><td  class=linkList><div class=linkList>&nbsp;</div></td>
<td id=footer>
<br>
  <p><a href="index.php">Home</a> | Site Map | 
  <a href="feedback.php">Feedback</a> | About Us | Contact Us | 
  <a href="shopping_cart.php">Shopping Cart</a><br>
  <br>
  This site is for educational purposes only.<br>
  The products are not for sale.</p>
</td><td  class=linkList2><div class=linkList2>&nbsp;</div></td></tr></table>
</BODY>
</HTML>
<?php    
   mysql_close($conn); 
   mysql_free_result($rs); ?>