<?php 

   $cqry = array(
    "CREATE TABLE Words (ListID int,  Word char(20) primary key, Definition char(255));",
"INSERT INTO Words VALUES (1, 'Accolade', 'praise, distinction, fame');",
"INSERT INTO Words VALUES (1, 'Accord', 'agreement, harmony');",
"INSERT INTO Words VALUES (1, 'Acumen', 'intellect, ability, talent');",
"INSERT INTO Words VALUES (1, 'Ambidextrous', 'able to skillfully use both hands');",
"INSERT INTO Words VALUES (1, 'Ample', 'a good supply, enough');",
"INSERT INTO Words VALUES (1, 'Amputate', 'to cut off, to remove');",
"INSERT INTO Words VALUES (1, 'Analogous', 'a study of similarities, a relationship');",
"INSERT INTO Words VALUES (1, 'Analogy', 'comparative, similar');",
"INSERT INTO Words VALUES (1, 'Anarchy', 'chaos, confusion, no law or order');",
"INSERT INTO Words VALUES (1, 'Anesthetic', 'a device to remove feeling or sensation');",
"INSERT INTO Words VALUES (1, 'Animated', 'lively, moving quickly');",
"INSERT INTO Words VALUES (1, 'Ashen', 'pale frightened');",
"INSERT INTO Words VALUES (1, 'Askew', 'crooked, deformed');",
"INSERT INTO Words VALUES (1, 'Aspiration', 'competitor, candidate, applicant');",
"INSERT INTO Words VALUES (1, 'Assail', 'to attack');",
"INSERT INTO Words VALUES (1, 'Assertive', 'aggressive, forceful, confident');",
"INSERT INTO Words VALUES (1, 'Astral', 'relating to the stars');",
"INSERT INTO Words VALUES (1, 'Astringent', 'harsh, bitter');",
"INSERT INTO Words VALUES (1, 'Atrocity', 'outrage, a major sin');",
"INSERT INTO Words VALUES (1, 'Benevolent', 'kind, generous, good-hearted');",
"INSERT INTO Words VALUES (1, 'Bestial', 'behaving like an animal, savage');",
"INSERT INTO Words VALUES (1, 'Bestow', 'to give, to inherit');",
"INSERT INTO Words VALUES (1, 'Bias', 'prejudice, a judgment');",
"INSERT INTO Words VALUES (1, 'Bizarre', 'Strange, incredible unusual');",
"INSERT INTO Words VALUES (1, 'Blasphemous', 'sacrilegious');",
"INSERT INTO Words VALUES (1, 'Buffet', 'a blow, or a punch');",
"INSERT INTO Words VALUES (1, 'Carrion', 'a decaying body, a corpse');",
"INSERT INTO Words VALUES (2, 'Castigate', 'to scold, to yell at, to belittle');",
"INSERT INTO Words VALUES (2, 'Casualty', 'an accident, a fatality');",
"INSERT INTO Words VALUES (2, 'Catharsis', 'an emotional experience');",
"INSERT INTO Words VALUES (2, 'Cauterize', 'to burn in order to stop the bleeding');",
"INSERT INTO Words VALUES (2, 'Cavalcade', 'a parade, a procession');",
"INSERT INTO Words VALUES (2, 'Certify', 'to confirm as true or accurate');",
"INSERT INTO Words VALUES (2, 'Charlatan', 'a fake or imposter');",
"INSERT INTO Words VALUES (2, 'Chronic', 'occurring or lasting a long time');",
"INSERT INTO Words VALUES (2, 'Cleave', 'to split in two2 to cut apart');",
"INSERT INTO Words VALUES (2, 'Clemency', 'mercy or forgiveness');",
"INSERT INTO Words VALUES (2, 'Cliché', 'an over-used expression');",
"INSERT INTO Words VALUES (2, 'Cloistered', 'out of the way, hidden, secluded');",
"INSERT INTO Words VALUES (2, 'Cogitate', 'to think, to use one\'s mind');",
"INSERT INTO Words VALUES (2, 'Collaborate', 'to join in, to work together, to help');",
"INSERT INTO Words VALUES (3, 'Conciliatory', 'desiring to make peace, agreeable');",
"INSERT INTO Words VALUES (3, 'Concur', 'to agree');",
"INSERT INTO Words VALUES (2, 'Connotation', 'a suggested meaning of a word');",
"INSERT INTO Words VALUES (2, 'Consecrate', 'to make sacred, to make holy');",
"INSERT INTO Words VALUES (2, 'Consort', 'to befriend, to associate');",
"INSERT INTO Words VALUES (3, 'Contentious', 'aggressive, looking for a fight');",
"INSERT INTO Words VALUES (2, 'Contiguous', 'joined in order, connected');",
"INSERT INTO Words VALUES (3, 'Covetous', 'greedy, possessive');",
"INSERT INTO Words VALUES (3, 'Crescendo', 'a gradual increase in volume');",
"INSERT INTO Words VALUES (3, 'Curmudgeon', 'a complaining person');",
"INSERT INTO Words VALUES (3, 'Deciduous', 'shedding leaves annually');",
"INSERT INTO Words VALUES (2, 'Defamation', 'a lie, a slander');",
"INSERT INTO Words VALUES (2, 'Deference', 'a show of respect or courtesy');",
"INSERT INTO Words VALUES (2, 'Deflect', 'to turn aside, to redirect');",
"INSERT INTO Words VALUES (3, 'Deluge', 'a flood or downpour');",
"INSERT INTO Words VALUES (3, 'Despondent', 'depressed, sad');",
"INSERT INTO Words VALUES (2, 'Dexterous', 'clever, skillful, slick');",
"INSERT INTO Words VALUES (2, 'Dictum', 'an announcement, a declaration');",
"INSERT INTO Words VALUES (3, 'Diffuse', 'to spread out , to scatter apart');",
"INSERT INTO Words VALUES (2, 'Digress', 'to wander, to stray');",
"INSERT INTO Words VALUES (2, 'Dire', 'an accident, a fatality');",
"INSERT INTO Words VALUES (3, 'Disburse', 'to expend with money, to pay out');",
"INSERT INTO Words VALUES (3, 'Dissonant', 'unpleasant to the ear, harsh');",
"INSERT INTO Words VALUES (3, 'Dolt', 'a stupid person, foolish');",
"INSERT INTO Words VALUES (2, 'Effervesce', 'to sparkle, to bubble');",
"INSERT INTO Words VALUES (2, 'Egotism', 'vanity, over-confidence');",
"INSERT INTO Words VALUES (3, 'Elegy', 'a remembrance for the dead');",
"INSERT INTO Words VALUES (3, 'Ennui', 'boredom, sluggishness');",
"INSERT INTO Words VALUES (2, 'Epoch', 'a period of time, an era');",
"INSERT INTO Words VALUES (2, 'Erie', 'strange, bizarre, unusual');",
"INSERT INTO Words VALUES (2, 'Erode', 'to waste, to wear down');",
"INSERT INTO Words VALUES (3, 'Erudite', 'scholarly, very intelligent');",
"INSERT INTO Words VALUES (3, 'Feign', 'to pretend');",
"INSERT INTO Words VALUES (3, 'Gourmand', 'a gourmet, one who lives to eat');",
"INSERT INTO Words VALUES (3, 'Hedonist', 'one who lives only for pleasure');",
"INSERT INTO Words VALUES (3, 'Herbivorous', 'eating only plants');",
"INSERT INTO Words VALUES (3, 'Hone', 'to sharpen');",
"INSERT INTO Words VALUES (3, 'Illicit', 'illegal, against the law');",
"INSERT INTO Words VALUES (3, 'Imbroglio', 'a bitter disagreement');",
"INSERT INTO Words VALUES (3, 'Immutable', 'unchangeable, consistent');",
"INSERT INTO Words VALUES (3, 'Impervious', 'not able to be harmed');",
"INSERT INTO Words VALUES (3, 'Inane', 'silly or foolish');",
"INSERT INTO Words VALUES (3, 'Incipient', 'beginning, early');",
"INSERT INTO Words VALUES (3, 'Incumbent', 'an elected politician who holds office');",
"INSERT INTO Words VALUES (3, 'Internment', 'burial');",
"INSERT INTO Words VALUES (3, 'Intrinsic', 'essential, basic, important');",
"INSERT INTO Words VALUES (4, 'Palpable', 'easy to see, obvious, having shape');",
"INSERT INTO Words VALUES (4, 'Paltry', 'small, little, a small amount');",
"INSERT INTO Words VALUES (4, 'Panacea', 'a remedy for disease, a cure-all');",
"INSERT INTO Words VALUES (4, 'Pandemonium', 'confusion, chaos');",
"INSERT INTO Words VALUES (4, 'Placid', 'calm, peaceful');",
"INSERT INTO Words VALUES (4, 'Plagiarism', 'using a source without giving credit');",
"INSERT INTO Words VALUES (4, 'Platitude', 'cliché, over-used expression of advise');",
"INSERT INTO Words VALUES (4, 'Plebeian', 'related to the common people, common');",
"INSERT INTO Words VALUES (4, 'Plethora', 'a large amount, a large group');",
"INSERT INTO Words VALUES (4, 'Prelude', 'an introduction, a beginning');",
"INSERT INTO Words VALUES (4, 'Preposterous', 'unlikely to occur, not possible');",
"INSERT INTO Words VALUES (4, 'Prevaricate', 'to lie, to not tell the truth');",
"INSERT INTO Words VALUES (4, 'Procrastinate', 'to postpone, to put off, to delay');",
"INSERT INTO Words VALUES (4, 'Rancor', 'anger, hatred');",
"INSERT INTO Words VALUES (4, 'Rant', 'to yell, to scream');",
"INSERT INTO Words VALUES (4, 'Ravenous', 'extremly hungry, famished');",
"INSERT INTO Words VALUES (4, 'Recapitulate', 'to repeat, to summarize breifly');",
"INSERT INTO Words VALUES (4, 'Renegade', 'someone who betrays his country, a traitor');",
"INSERT INTO Words VALUES (4, 'Renovate', 'to restore, to fix-up');",
"INSERT INTO Words VALUES (4, 'Reprimand', 'to correct, to discipline');",
"INSERT INTO Words VALUES (4, 'Revere', 'to adore, to love');",
"INSERT INTO Words VALUES (4, 'Sanguinary', 'bloody, murderous');",
"INSERT INTO Words VALUES (4, 'Savoir Faire', 'a sophistication, a socail skill or ability');",
"INSERT INTO Words VALUES (4, 'Specious', 'false, not true, deceptive');",
"INSERT INTO Words VALUES (4, 'Squalid', 'filthy, dirty');",
"INSERT INTO Words VALUES (4, 'Stamina', 'strength, endurence');",
"INSERT INTO Words VALUES (4, 'Stigmatize', 'to isolate, to mark with disgrace');",
"INSERT INTO Words VALUES (4, 'Stripend', 'an amount of money, cash wages');",
"INSERT INTO Words VALUES (4, 'Tactile', 'easy to shape, to move or to touch');",
"INSERT INTO Words VALUES (4, 'Taint', 'to infect or to make impure');"

   );
    

  require('db.inc');
  echo executeUpdatePHP($cqry);

  function executeUpdatePHP($as)
  {   
        $m = "";
        foreach($as as $value) {
           mysql_query($value) or die('Query failed: ' . mysql_error() . '<br>' . $m);
           $m = $m . $value . "<br>";
        }
     return $m;
  }
?>
